name: Check Directory

on: 
 push:
  branches:
    - master

jobs:
  check-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: |
          echo "Current Directory:"
          pwd
